config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  resources :users
  resources :jobs
  resources :sessions

  post :login, to: "sessions#create"
  delete :logout, to: "sessions#logout"
  get :logged_in, to: "sessions#logged_in"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :jobs

    has_secure_password 

    validates_presence_of :email
    validates_uniqueness_of :email

    def userHandle
        return self.email.split("@")[0].capitalize
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

app/controllers/concerns/current_user_concern.rb
# module CurrentUserConcern
#     extend ActiveSupport::Concern

#     include do
#         before_action :set_current_user
#     end

#     def set_current_user
#         if session[:user_id]
#             @current_user = User.find(session[:user_id])
#         end
#     end
# end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :authorize, except: [:show, :index]

  def index
    @jobs = Job.all.order("Created_At DESC")
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @job = Job.find(params[:id])
    @job.update(job_params)
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  
  def create
    log_in
  end

  def logged_in
    check_if_logged_in
  end

  def logout
    log_out
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!

    def new
        @user = User.new
        render json: @user
    end

    def show
        @user = User.find(params[:id])
        render json: @user
    end

    def create
        user = User.create(user_params)

        if user.valid?
            user.save
            session[:user_id] = user.id

            render json: {
                status: "created",
                logged_in: true,
                user: user
            }
        else
            render json: {status: 500}
        end
    end

    def edit
        @user = User.find(params[:id])
        render json: @user
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)

        if @user.update(user_params)
            render json: @user
        else
            render json: @user.errors
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy

        render json: "Deleted Successfully"
    end


    private

    def user_params
        params.require(:user).permit(:email,:password,:password_confirmation)
    end

end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # Login
    def log_in
        user = User
        .find_by(email: params["user"]["email"])
        .authenticate(params["user"]["password"])

        if user 
            session[:user_id] = user.id
            render json:{
                status: :created,
                logged_in: true,
                user: user
            }
        else
            render json: {status: 401}
        end
    end
    

   # Returns the current logged-in user (if any)
  def current_user
    if session[:user_id] == user.id
        @current_user ||= User.find(session[:user_id])  if session[:user_id]  
    end
  end


  # Check if user is logged_in
  def check_if_logged_in
     if @current_user
      render json: {
        logged_in: true,
        user: @current_user
      }
    else
       render json: {
        logged_in: false
      }
    end
  end

  # Logs out the current user
  def log_out
    reset_session
     render json: {
        status:200,
        logged_out: true
      }
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
<% if job.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

    <ul>
        <% job.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
</div>

<div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
</div>

<button type="submit" class="btn btn-primary">Save</button>

<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<%= link_to 'Create New Job', new_job_path, class: "btn btn-primary" %>


<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Body</th>
            <th>User</th>
            <th>Date Post</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        <% @jobs.each do |job| %>
        <tr>
            <td><%= job.title %></td>
            <td><%= job.body %></td>
            <td><%= job.user.userHandle %></td>
            <td><%= job.created_at.strftime("%d/%m/%Y") %></td>
            <td><%= link_to 'Show', job, class: "btn btn-info" %>
                <% if logged_in? && (current_user == job.user || current_user.admin?) %>
                | <%= link_to 'Edit', edit_job_path(job), class: "btn btn-success" %> |
                <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

app/views/jobs/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @job.title %>
</p>

<p>
    <strong>Body:</strong>
    <%= @job.body %>
</p>

<p>
    <strong>User:</strong>
    <%= @job.user.userHandle %>
</p>

<% if current_user == @job.user %>
<%= link_to 'Edit', edit_job_path(@job), class: "btn btn-success" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Authentication App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
    <nav class="nav">
        <div class="container-fluid">
            <a href="/"><img src="<%= asset_path('logo3.png') %>" /></a>

            <ul>
                <li><a href="/">HOME</a></li>
                <li><a href="/jobs">JOBS</a></li>

                <% if logged_in? %>
                <span style="float:right; margin-right:30px">
                    <li><a href=" /users/<%= current_user.id %>">MY PROFILE</a></li>
                    <li><a href="/logout" data-confirm="Are you sure?">LOG OUT</a></li>
                </span>

                <% else %>
                <span style="float:right; margin-right:30px">
                    <li><a href="/signup">SIGN UP</a></li>
                    <li><a href="/login">LOG IN</a></li>
                </span>
                <% end %>

            </ul>
        </div>
    </nav>

    <div class="container">
        <%= yield %>
    </div>
</body>

</html>

app/views/pages/home.html.erb
<h1>Home</h1>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for @user do |f| %>

<div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
</div>

<div class="form-group">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
</div>

<div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
</div>

<button type="submit" class="btn btn-primary">Sign Up</button>

<% end %>

app/views/users/show.html.erb
<h1><%= current_user.userHandle %> Profile </h1>

<p>
    <strong>Name:</strong>
    <%= @user.userHandle %>
</p>

<p>
    <strong>Email:</strong>
    <%= @user.email %>
</p>